version: "3.3"
services:
    web:
      image: 7oda/static
      depends_on:
        - api
      ports:
        - "80:90"
      links: 
        - api
    api:
      image: 7oda/node-web-app
      ports:
        - "7000:5000"
      command: [ "npm", "start" ]
